In [2]:
# Python Review

Goals: 
- recall basic python vocab
- practice markdown

## Libraries and packages

**library**: a collection of code that we can use to perform specific tasks in our program

**NumPy**:
- core library for numerical computing in Python
- many other libraries use NumPy arrays as building blocks
- computations on NumPy are optiomized for speed and memory usage

Let's import NumPy with **standard abbreviation**

SyntaxError: unterminated string literal (detected at line 16) (3308359969.py, line 16)

In [3]:
import numpy as np

## Varibles

**variable** a name we assign to a particular object in Python

Example:

In [4]:
# Assign a small array to a variable

a = np.array([[1,1,2],[3,5,8]])

In [5]:
# Run the cell with a variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [6]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**object** is a bundle of *properties* and *actions* about something specific.

Example:

Object: data frame

Properties: number rows, names of the columns, date created

Action: selecting a specific row, adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables

In practice, we can often use variable and object interchangeably.

In [7]:
print(a)

# Check the type/class of a variable/object by using `type` function
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [8]:
print(a[0,0])

# Check the type on an entry on the array by indexing
type(a[0,0])

1


numpy.int64

Notice that `type(a[0,0])` is `numpy.int64` and not just the standard Python integer type. This is telling us that 1 is an integer stored as a 64-bit number

In [9]:
a[1,1]

5

## Functions 
`print` was our first example of a Python **function**

Functions take in a set of **arguments** and those arguments create an **output**.

argument = parameter

We can ask information about a function by executing `function`

In [10]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**.