# Python Review

Goals: 
- recall basic python vocab
- practice markdown

## Libraries and packages

**library**: a collection of code that we can use to perform specific tasks in our program

**NumPy**:
- core library for numerical computing in Python
- many other libraries use NumPy arrays as building blocks
- computations on NumPy are optiomized for speed and memory usage

Let's import NumPy with **standard abbreviation**

In [3]:
import numpy as np

## Varibles

**variable** a name we assign to a particular object in Python

Example:

In [4]:
# Assign a small array to a variable

a = np.array([[1,1,2],[3,5,8]])

In [5]:
# Run the cell with a variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [6]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**object** is a bundle of *properties* and *actions* about something specific.

Example:

Object: data frame

Properties: number rows, names of the columns, date created

Action: selecting a specific row, adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables

In practice, we can often use variable and object interchangeably.

In [7]:
print(a)

# Check the type/class of a variable/object by using `type` function
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [8]:
print(a[0,0])

# Check the type on an entry on the array by indexing
type(a[0,0])

1


numpy.int64

Notice that `type(a[0,0])` is `numpy.int64` and not just the standard Python integer type. This is telling us that 1 is an integer stored as a 64-bit number

In [9]:
a[1,1]

5

## Functions 
`print` was our first example of a Python **function**

Functions take in a set of **arguments** and those arguments create an **output**.

argument = parameter

We can ask information about a function by executing `function`

In [10]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**.

## Attributes & methods

An object in Python has attributes and methods

- **attribute**: a property of an object, some piece of information about it
- **method**: a procedure associated with the object, an action where the main ingredient is the object

### Check-in

Fish attributes:

- length, color, species
- die(), bite(), swim()

**Example** 
Attributes for `numpy.arrays`

We can access a variable's attributes and methods by adding a period `.` at the end of the variable's name.

`variable.method()` or `variable.attribute`


In [11]:
a.shape

(2, 3)

In [12]:
type(a.shape)

tuple

In [13]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [14]:
# Methods examples
# min() returns the minimum value along a specifies axis
a.min(axis=0)

array([1, 1, 2])

## Check-In
We can also call the `min` method without any parameters

In [16]:
a.min()

1

Remember: methods are functions associated with an object

In [17]:
type(a.min)

builtin_function_or_method

## Exercise

1. Read the `print` function help. What is the **type** of the argument `sep`? IS this an optional or non-optional argument? Why?

2. Create two new variables, one with the integer value 77 and another one with the string 99.

3. Use your variables to print `77%99%77` by changing the value of one of the optional arguments in `print`

In [18]:
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [22]:
b = 77
c = '99'

In [23]:
print(b,c,b)

77 99 77


In [24]:
print(b,c,b, sep = '%')

77%99%77
